version: '3.9'

services:
  api:
    container_name: api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 9001:8000
    environment:
      - DEBUG=1
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=test
      - DB_HOST=db
      - DB_PORT=5432
  db:
    container_name: db
    image: postgres:14.0-alpine3.14
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
